"""
📝 DevOps Interview Q&A Module
Curated interview questions with quiz mode
"""

import random

QUESTIONS = {
    "docker": [
        {
            "q": "What is the difference between a Docker image and a container?",
            "a": "An **image** is a read-only template with instructions for creating a container. A **container** is a runnable instance of an image.",
            "a_si": "**Image** එකක් කියන්නේ container එකක් හදන්න instructions තියෙන read-only template එකක්. **Container** එකක් කියන්නේ image එකක runnable instance එකක්."
        },
        {
            "q": "What is a Dockerfile?",
            "a": "A **Dockerfile** is a text file with instructions to build a Docker image. It contains commands like FROM, RUN, COPY, CMD.",
            "a_si": "**Dockerfile** එකක් කියන්නේ Docker image එකක් build කරන්න instructions තියෙන text file එකක්."
        },
        {
            "q": "What is Docker Compose?",
            "a": "**Docker Compose** is a tool for defining and running multi-container applications using a YAML file (docker-compose.yml).",
            "a_si": "**Docker Compose** කියන්නේ multi-container applications run කරන්න use කරන tool එකක්."
        },
        {
            "q": "What is the difference between CMD and ENTRYPOINT?",
            "a": "**CMD** provides default arguments that can be overridden. **ENTRYPOINT** defines the main command that always runs.",
            "a_si": "**CMD** default arguments දෙනවා (override කරන්න පුළුවන්). **ENTRYPOINT** main command define කරනවා."
        },
        {
            "q": "What are Docker volumes?",
            "a": "**Volumes** are the preferred way to persist data generated by containers. They are managed by Docker and survive container restarts.",
            "a_si": "**Volumes** kියන්නේ container data persist කරන්න best way එක. Docker manage කරනවා."
        }
    ],
    "kubernetes": [
        {
            "q": "What is a Kubernetes Pod?",
            "a": "A **Pod** is the smallest deployable unit in K8s. It can contain one or more containers that share storage and network.",
            "a_si": "**Pod** එකක් කියන්නේ K8s වල deploy කරන්න පුළුවන් කුඩාම unit එක."
        },
        {
            "q": "What is a Deployment in Kubernetes?",
            "a": "A **Deployment** manages ReplicaSets and provides declarative updates, rolling updates, and rollback capabilities.",
            "a_si": "**Deployment** එකක් ReplicaSets manage කරනවා, rolling updates සහ rollback දෙනවා."
        },
        {
            "q": "What is the difference between a Service and an Ingress?",
            "a": "A **Service** exposes pods internally (ClusterIP) or externally (LoadBalancer). **Ingress** manages external HTTP/HTTPS routing with URL-based rules.",
            "a_si": "**Service** pods expose කරනවා. **Ingress** external HTTP routing manage කරනවා."
        },
        {
            "q": "What is a ConfigMap?",
            "a": "A **ConfigMap** stores non-confidential configuration data as key-value pairs that can be consumed by pods.",
            "a_si": "**ConfigMap** non-confidential config data store කරනවා."
        },
        {
            "q": "What is a StatefulSet?",
            "a": "A **StatefulSet** manages stateful applications with stable network IDs and persistent storage. Used for databases.",
            "a_si": "**StatefulSet** stateful apps manage කරනවා - databases වලට use කරනවා."
        }
    ],
    "cicd": [
        {
            "q": "What is CI/CD?",
            "a": "**CI** (Continuous Integration) automates code integration and testing. **CD** (Continuous Delivery/Deployment) automates deployment to production.",
            "a_si": "**CI** code integration automate කරනවා. **CD** deployment automate කරනවා."
        },
        {
            "q": "What is a GitHub Actions workflow?",
            "a": "A YAML file that defines automated tasks triggered by events like push or pull request. Consists of jobs with steps.",
            "a_si": "Push/PR වගේ events වලින් trigger වෙන automated tasks define කරන YAML file එකක්."
        },
        {
            "q": "What is the difference between CI and CD?",
            "a": "**CI** focuses on automated testing and integration. **CD** focuses on automated deployment. CI happens before CD.",
            "a_si": "**CI** testing/integration. **CD** deployment. CI first, CD after."
        }
    ],
    "linux": [
        {
            "q": "What does the chmod command do?",
            "a": "**chmod** changes file permissions. Example: `chmod 755 file.sh` gives owner full access, others read+execute.",
            "a_si": "**chmod** file permissions change කරනවා."
        },
        {
            "q": "How do you find a process using a specific port?",
            "a": "Use `lsof -i :PORT` or `netstat -tlnp | grep PORT` or `ss -tlnp | grep PORT`",
            "a_si": "`lsof -i :PORT` හෝ `netstat -tlnp | grep PORT` use කරන්න."
        },
        {
            "q": "What is the difference between hard link and soft link?",
            "a": "**Hard link** points to inode (survives original deletion). **Soft/symbolic link** points to filename (breaks if original deleted).",
            "a_si": "**Hard link** inode එකට point කරනවා. **Soft link** filename එකට point කරනවා."
        }
    ],
    "devops": [
        {
            "q": "What is Infrastructure as Code (IaC)?",
            "a": "**IaC** is managing infrastructure using code/config files instead of manual processes. Tools: Terraform, Ansible, Pulumi.",
            "a_si": "**IaC** කියන්නේ infrastructure code වලින් manage කරන එක. Terraform, Ansible use කරනවා."
        },
        {
            "q": "What is the difference between Terraform and Ansible?",
            "a": "**Terraform** is for provisioning infrastructure (declarative). **Ansible** is for configuration management (procedural/declarative).",
            "a_si": "**Terraform** infrastructure provision කරනවා. **Ansible** configuration manage කරනවා."
        },
        {
            "q": "What is GitOps?",
            "a": "**GitOps** uses Git as the single source of truth for declarative infrastructure. Changes are made via pull requests.",
            "a_si": "**GitOps** Git එක infrastructure සඳහා single source of truth විදිහට use කරනවා."
        }
    ]
}


class QuizSession:
    def __init__(self):
        self.current_question = None
        self.score = 0
        self.total = 0
        self.category = None
    
    def start(self, category: str = None):
        self.score = 0
        self.total = 0
        self.category = category
        return self.next_question()
    
    def next_question(self) -> dict:
        if self.category and self.category in QUESTIONS:
            questions = QUESTIONS[self.category]
        else:
            questions = [q for qs in QUESTIONS.values() for q in qs]
        
        self.current_question = random.choice(questions)
        self.total += 1
        
        return {
            "question": self.current_question["q"],
            "number": self.total,
            "category": self.category or "mixed"
        }
    
    def reveal_answer(self, lang: str = "en") -> str:
        if not self.current_question:
            return "No active question"
        
        answer_key = "a_si" if lang == "si" else "a"
        answer = self.current_question.get(answer_key, self.current_question["a"])
        
        return f"📖 **Answer:**\n\n{answer}"
    
    def get_score(self) -> str:
        return f"📊 **Score:** {self.score}/{self.total}"


# Global quiz sessions per user
quiz_sessions = {}


def get_quiz_session(user_id: str) -> QuizSession:
    if user_id not in quiz_sessions:
        quiz_sessions[user_id] = QuizSession()
    return quiz_sessions[user_id]


def get_random_question(category: str = None, lang: str = "en") -> dict:
    """Get a random question"""
    if category and category in QUESTIONS:
        questions = QUESTIONS[category]
    else:
        questions = [q for qs in QUESTIONS.values() for q in qs]
    
    q = random.choice(questions)
    answer_key = "a_si" if lang == "si" else "a"
    
    return {
        "question": q["q"],
        "answer": q.get(answer_key, q["a"])
    }


def get_interview_menu():
    return """📝 **DevOps Interview Q&A**

**Categories:**
• `/quiz docker` - Docker questions
• `/quiz kubernetes` - K8s questions
• `/quiz cicd` - CI/CD questions
• `/quiz linux` - Linux questions
• `/quiz devops` - DevOps concepts
• `/quiz` - Random mix

**Commands:**
• `/answer` - Show answer
• `/next` - Next question
• `/score` - See your score

💡 _50+ curated interview questions!_"""


def get_categories():
    return list(QUESTIONS.keys())
